### ISSUE TITLE
After update to 0.3.2 I can neither add devices nor use existing ones.

### ISSUE THREAD

**Issue by AngryLasagna** [nextcloud/twofactor_webauthn#263] opened 2022-09-22 14:28 UTC
### Steps to reproduce
1. Upgrade plugin to 0.3.2 from previous version
2. Try login with webauthn as 2nd factor.
3. Try re-adding webauthn device in settings and repeat 2

### Expected behaviour
Existing pairings should work.

### Actual behaviour
On login I get an error that I should try another device because this one does not have a pairing.
On re-add I get an unspecific error "Server-Fehler beim Versuch die WebAuthn-Geräte-Registrierung abzuschließen".
Which roughly translates to "Server-Error while trying to complete Webauthn device registration".

### Server configuration

**Operating system**:
Docker on Embedded Linux

**Web server:**
NGINX -> Apache in Nextcloud container

**Database:**
Postgres on Alpine container

**PHP version:**
Whatever official Nextcloud container ships. Currently 8.0.23

**Version:** (see admin page)
0.3.2

**Updated from an older version or fresh install:**
Updated from previous version.

**List of activated apps:**
No

**The content of config/config.php:**
No

#### Client configuration
**Browser:**
Chromium and Firefox

**Operating system:**
Linux x86_64

##### Web server error log

Nothing in context

##### Server log (data/nextcloud.log)
Unreadable JSON mess I can't bother to filter.

##### Browser log
```
Insert your browser log here, this could for example include:
![image](https://user-images.githubusercontent.com/57591331/191774082-9ea871fd-6aff-459c-ac74-76cb686a1c44.png)

Chromium does not seem to log network stuff about webauthn.
```

**Comment by ChristophWurst** [comment] 2022-09-22 15:36
> Browser log

so? any details?

**Comment by zevlee** [comment] 2022-10-05 22:33
I can confirm the same error when attempting to register a new key.

```
[index] Error: OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'public_key_credential_id' at row 1 at <<closure>>

 0. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 329
    OC\DB\Exceptions\DbalException::wrap()
 1. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 139
    OC\DB\QueryBuilder\QueryBuilder->executeStatement()
 2. /var/www/nextcloud/apps/twofactor_webauthn/lib/Db/PublicKeyCredentialEntityMapper.php line 132
    OCP\AppFramework\Db\QBMapper->insert()
 3. /var/www/nextcloud/apps/twofactor_webauthn/lib/Repository/WebauthnPublicKeyCredentialSourceRepository.php line 91
    OCA\TwoFactorWebauthn\Db\PublicKeyCredentialEntityMapper->insertOrUpdate()
 4. /var/www/nextcloud/apps/twofactor_webauthn/lib/Service/WebAuthnManager.php line 233
    OCA\TwoFactorWebauthn\Repository\WebauthnPublicKeyCredentialSourceRepository->saveCredentialSource()
 5. /var/www/nextcloud/apps/twofactor_webauthn/lib/Controller/SettingsController.php line 68
    OCA\TwoFactorWebauthn\Service\WebAuthnManager->finishRegister()
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\TwoFactorWebauthn\Controller\SettingsController->finishRegister()
 7. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
 8. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
 9. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
10. /var/www/nextcloud/lib/base.php line 1030
    OC\Route\Router->match()
11. /var/www/nextcloud/index.php line 36
    OC::handleRequest()
```

**Comment by ChristophWurst** [comment] 2022-10-06 06:16
Duplicate of https://github.com/nextcloud/twofactor_webauthn/issues/233

**Closed** 2022-10-06 06:16 UTC
